name 'ruby-on-rails-dev-box'
maintainer 'vnegrisolo'
maintainer_email 'vinicius.negrisolo@gmail.com'
license 'All rights reserved'
description 'Installs/Configures ruby-on-rails-dev-box'
long_description 'Installs/Configures ruby-on-rails-dev-box'
version '0.0.1'

depends 'apt'
depends 'git'
