name 'ruby-on-rails-dev-box'
maintainer 'vnegrisolo'
maintainer_email 'vinicius.negrisolo@gmail.com'
license 'All rights reserved'
description 'Installs/Configures ruby-on-rails-dev-box'
long_description 'Installs/Configures ruby-on-rails-dev-box'
version '0.0.1'

supports 'ubuntu'
supports 'debian'

depends 'build-essential'
depends 'locale'
depends 'apt'
depends 'htop'
depends 'git'
depends 'oh-my-zsh'
depends 'ruby_build'
depends 'rbenv'
depends 'redisio'
depends 'nginx'
depends 'elasticsearch-ng'
depends 'postgresql'
depends 'mysql'
depends 'nodejs'
